spring.application.name=studhunt-ai

OPENAI_API_KEY=your_api_key_here
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d75p9l7diees73fcfpvg-a.singapore-postgres.render.com:5432/studhunt
spring.datasource.username=studhunt_user
spring.datasource.password=nBz33h1ij9tGkswpbqCTFbQ0gljWK6aC

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true